"""Add: Name Col in Completed

Revision ID: 916c14deb2b5
Revises: cfccbd157115
Create Date: 2025-07-23 18:22:19.060293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916c14deb2b5'
down_revision = 'cfccbd157115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_interns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_interns', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
