"""Add: Is Excellence Column

Revision ID: 6144844340dc
Revises: 916c14deb2b5
Create Date: 2025-07-23 18:34:43.185317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6144844340dc'
down_revision = '916c14deb2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_interns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excellence', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_interns', schema=None) as batch_op:
        batch_op.drop_column('excellence')

    # ### end Alembic commands ###
