"""Add: Completed Tables

Revision ID: cfccbd157115
Revises: 43ceb68ca22b
Create Date: 2025-07-22 19:47:32.562114
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cfccbd157115'
down_revision = '43ceb68ca22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_interns', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_completed_interns_internship_code',  # <- Add a name
            'completed_internships',
            ['internship_code'],
            ['internship_code']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_interns', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_completed_interns_internship_code',  # <- Use the same name
            type_='foreignkey'
        )
    # ### end Alembic commands ###
