"""Add: Grade columns

Revision ID: 01a383b66d44
Revises: 2e18e9017722
Create Date: 2025-07-04 14:33:26.872351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a383b66d44'
down_revision = '2e18e9017722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intern_final_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intern_final_assignment', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
