"""OTP

Revision ID: 14c2a1401d2b
Revises: 2348cd021c9b
Create Date: 2025-06-22 12:48:05.474752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c2a1401d2b'
down_revision = '2348cd021c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=150), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('verify_for', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mfa_verification')
    # ### end Alembic commands ###
