"""Internship & Profile

Revision ID: 2348cd021c9b
Revises: ef48974d5de6
Create Date: 2025-06-22 11:27:51.287101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2348cd021c9b'
down_revision = 'ef48974d5de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_join', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean()))
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.drop_column('can_join')

    # ### end Alembic commands ###
