"""HR FK Fix

Revision ID: 290730aa8b04
Revises: c9350cf85c7b
Create Date: 2025-06-22 20:02:54.872377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290730aa8b04'
down_revision = 'c9350cf85c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.alter_column('hr_profile_id',
               existing_type=sa.String(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.alter_column('hr_profile_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
