"""Add: Final Assignment Submission

Revision ID: 2e18e9017722
Revises: 7143f21eaa46
Create Date: 2025-06-30 10:18:39.172515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e18e9017722'
down_revision = '7143f21eaa46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intern_final_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('assignment_url', sa.String(length=512), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intern_final_assignment')
    # ### end Alembic commands ###
