"""Add: Is Excellence 

Revision ID: 43ceb68ca22b
Revises: 01a383b66d44
Create Date: 2025-07-04 21:20:15.869173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ceb68ca22b'
down_revision = '01a383b66d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intern_final_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isExcellence', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intern_final_assignment', schema=None) as batch_op:
        batch_op.drop_column('isExcellence')

    # ### end Alembic commands ###
