"""Add: Completed Tables

Revision ID: 4d2ba185b3fd
Revises: 43ceb68ca22b
Create Date: 2025-07-23 19:44:22.123811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2ba185b3fd'
down_revision = '43ceb68ca22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('stipend', sa.String(length=50), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('hr_profile_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['hr_profile_id'], ['profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internship_code')
    )
    op.create_table('completed_interns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('excellence', sa.Boolean(), nullable=True),
    sa.Column('internship_code', sa.String(length=64), nullable=False),
    sa.Column('completion_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['internship_code'], ['completed_internships.internship_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_interns')
    op.drop_table('completed_internships')
    # ### end Alembic commands ###
