"""empty message

Revision ID: 5252bfe12fa5
Revises: 5495dce7333f
Create Date: 2025-06-22 03:46:14.385204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5252bfe12fa5'
down_revision = '5495dce7333f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('revoked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revoked', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
