"""Internship & Apply

Revision ID: 703419eff77e
Revises: 5252bfe12fa5
Create Date: 2025-06-22 04:10:40.575873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703419eff77e'
down_revision = '5252bfe12fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('stipend', sa.String(length=50), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('internship_apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('resume_url', sa.String(length=300), nullable=True),
    sa.Column('applied_on', sa.DateTime(), nullable=True),
    sa.Column('internship_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['internship_code'], ['internships.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internship_apply')
    op.drop_table('internships')
    # ### end Alembic commands ###
