"""Datatype

Revision ID: 9d5809ba754d
Revises: 290730aa8b04
Create Date: 2025-06-23 20:51:34.728324

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5809ba754d'
down_revision = '290730aa8b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa_verification', schema=None) as batch_op:
        batch_op.alter_column('verify_for',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa_verification', schema=None) as batch_op:
        batch_op.alter_column('verify_for',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
